### ISSUE TITLE
Works fine but getting an error

### ISSUE THREAD

**Issue by rp1231** [rgomezjnr/wizctrl#6]
Hi, this works absolutely fine, but I get an error while  executing it via cmd

```
Exception ignored in: <function wizlight.__del__ at 0x0000025A84156440>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pywizlight\bulb.py", line 781, in __del__
    self.loop.call_soon_threadsafe(self._async_close)
  File "C:\Python310\lib\asyncio\base_events.py", line 795, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025A84038A60>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
Thought I'd post it here just in case.

Thanks

**Comment by djacobson** [comment]
Just curious, what version of pywizlight do you have installed? Mine below... FYI, pywizlight requires Python 3.

$ pip3 show pywizlight
Name: pywizlight
Version: 0.4.16
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: MIT
Location: /home/pi/src/pywizlight
Requires: asyncio-dgram, click
Required-by: wizcon

**Comment by rgomezjnr** [comment]
I think that error is due to newer versions of Python, as described in https://github.com/sbidy/pywizlight/issues/140. @sbidy created a commit to address this, so I think this should be addressed in an upcoming version of pywizlight.

**Comment by rp1231** [comment]
@rgomezjnr Glad to hear that!

@djacobson Here is my version of pywizlight
```
Name: pywizlight
Version: 0.5.13
Summary: A python connector for WiZ light bulbs (e.g SLV Play)
Home-page: https://github.com/sbidy/pywizlight
Author: Stephan Traub
Author-email: sbidy@hotmail.com
License: MIT
Location: c:\python310\lib\site-packages
Requires: click
Required-by: wizcon
```

Also I noticed that you've used a '$' before the actual command.
Why is that?
I always get this error when I use the $ sign:
```
$ pip3 show pywizlight
'$' is not recognized as an internal or external command,
operable program or batch file.
```
I've seen the $ sign before commands in many places but never could figure out what it was for?

Thanks

**Comment by rgomezjnr** [comment]
> Also I noticed that you've used a '$' before the actual command.

It's just part of the [command prompt](https://en.wikipedia.org/wiki/Command-line_interface#Command_prompt). You don't actually enter $ as part of the command in this case.

**Comment by rp1231** [comment]
Thanks for the explanation!

**Comment by vvenkatesh-ML** [comment]
I have been having this issue as well, but in my case, the bulb is not reacting. 
The pywizlight version I am using is: 0.5.14 with python 3.7. 
Additionally, my buld is A19 - 1.27.0 (23007)
Any help is appreciated!

**Comment by rgomezjnr** [comment]
@vvenkatesh-ML Here's some troubleshooting steps: 

1. Verify the IP address of the bulb, either using your router or the Wiz app on your phone
2. Try pinging the bulb e.g. `ping IP`
3. Try using [wizlight](https://github.com/sbidy/pywizlight#cli) command that comes installed with pywizlight e.g. `wizlight on`

**Comment by nickjwhite** [comment]
This issue is still present with the latest wizcon / pywizlight on pip. It doesn't look like anything has been changed in pywizlight - the [fix mentioned above](https://github.com/sbidy/pywizlight/commit/5164976b09b78e8ba3c8d79c6a92d415ccf0696c) was just a documentation change to example code which doesn't seem to make much difference.

A workaround (inspired by [this comment](https://github.com/sbidy/pywizlight/issues/140#issuecomment-1321426436) on the pywizlight issue) is to add `del wizlight.__del__` at the start of the `async def main()` function. I'm not much of a python programmer so I'm not sure if there is a better way to fix this (I imagine there is).

**Comment by rgomezjnr** [comment]
@rp1231 @nickjwhite Are you still seeing this issue? I'm not.

```sh
[rob@muthur ~]$ python --version
Python 3.14.6
[rob@muthur ~]$ pipx install wizcon
  installed package wizcon 0.3.0, installed using Python 3.14.6
  These apps are now available
    - wizcon
done! ✨ 🌟 ✨
[rob@muthur ~]$ wizcon -v
wizcon 0.3.0
[rob@muthur ~]$ wizcon $BULB_IP ON
[rob@muthur ~]$ wizcon $BULB_IP OFF
[rob@muthur ~]$ cat .local/share/pipx/venvs/wizcon/lib/python3.14/site-packages/pywizlight/_version.py
"""PyPi Version."""

__version__ = "0.6.5"
```

**Comment by rp1231** [comment]
The Issue seems to be solved!
Thanks

**Comment by nickjwhite** [comment]
I'm not able to test this at the moment, so fine by me to mark it solved 👍
